name: get_user_agent
description: Librería para obtener el user agent del navegador.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

repository: https://github.com/EduardoAyora/verify_instagram_navigator
